sections:
  - folder: "executive-summary"
    title: "Executive Summary"
    icon: "carbon:identification"

  - folder: "values"
    title: "Values & Vision"
    icon: "carbon:sprout"

  - folder: "skills-finance"
    title: "Skills: Finance"
    icon: "carbon:chart-line"

  - folder: "skills-strategy"
    title: "Skills: Strategy"
    icon: "carbon:strategy-play"

  - folder: "skills-cloud-ai"
    title: "Skills: Cloud & AI"
    icon: "carbon:chip"

  - folder: "thoughts"
    title: "Personal Development"
    icon: "carbon:chemistry"

  - folder: "projects"
    title: "Key Projects"
    icon: "carbon:code"

  - folder: "jobs"
    title: "Job History"
    icon: "carbon:portfolio"

  - folder: "education"
    title: "Academic Excellence"
    icon: "carbon:education"

  - folder: "social"
    title: "Social & Impact"
    icon: "carbon:share"

  - folder: "references"
    title: "Professional References"
    icon: "carbon:user-certification"

special:
  downloads:
    title: "Downloads"
    icon: "carbon:volume-file-storage"
